main: Creadores.Program.pluginMV
name: "Craftsmine"
description: "Allows you to join current servers with minecraft bedrock 0.15.10(Craftsman Old)"
author: "Creadores Program"
website: "https://github.com/Trollhunters501/Craftsmine/"
version: "${pom.version}"
api: ["1.0.0"]
load: STARTUP
